export const STAGE_CODES = {
  LEAD_SOURCED: "LEAD_SOURCED",
  REGISTRATION_LINK_SENT: "REGISTRATION_LINK_SENT",
  BUSINESS_REGISTERED: "BUSINESS_REGISTERED",
  APPLICATION_COMPLETED: "APPLICATION_COMPLETED",
  FOUNDATION_ONE_CONTRACT_SIGNED: "FOUNDATION_ONE_CONTRACT_SIGNED",
  EOI_REQUESTED: "EXPRESSION_OF_INTEREST_REQUESTED",
  EOI_UPLOADED: "EXPRESSION_OF_INTEREST_UPLOADED",
  EOI_SENT_TO_PARTNER: "EXPRESSION_OF_INTEREST_SENT_TO_PARTNER",
  EOI_APPROVED: "EXPRESSION_OF_INTEREST_APPROVED",
  UTILITY_BILL_REQUESTED: "UTILITY_BILL_REQUESTED",
  UTILITY_BILL_UPLOADED: "UTILITY_BILL_UPLOADED",
  UTILITY_BILL_SENT_TO_PARTNER: "UTILITY_BILL_SENT_TO_PARTNER",
  PROPOSAL_RECEIVED: "PROPOSAL_RECEIVED",
  PROPOSAL_DELIVERED: "PROPOSAL_DELIVERED_TO_BUSINESS",
  PROPOSAL_SIGNED: "PROPOSAL_SIGNED_BY_BUSINESS",
  PROPOSAL_SENT_TO_PARTNER: "PROPOSAL_SENT_TO_PARTNER",
  TERM_SHEET_RECEIVED: "TERM_SHEET_RECEIVED",
  TERM_SHEET_DELIVERED: "TERM_SHEET_DELIVERED_TO_BUSINESS",
  TERM_SHEET_SIGNED: "TERM_SHEET_SIGNED_BY_BUSINESS",
  TERM_SHEET_SENT_TO_PARTNER: "TERM_SHEET_SENT_TO_PARTNER",
  KYC_REQUESTED: "KNOW_YOUR_CUSTOMER_REQUESTED",
  KYC_UPLOADED: "KNOW_YOUR_CUSTOMER_UPLOADED",
  KYC_SENT_TO_PARTNER: "KNOW_YOUR_CUSTOMER_SENT_TO_PARTNER",
  NEDBANK_APPROVED: "NEDBANK_APPROVED",
  SITE_INSPECTION_STARTED: "SITE_INSPECTION_STARTED",
  INSTALLATION_IN_PROGRESS: "INSTALLATION_IN_PROGRESS",
  COMMISSIONED: "COMMISSIONED",
  ACTIVE_SUPPORT: "ACTIVE_SUPPORT",
  DISQUALIFIED: "DISQUALIFIED",
  LOST: "LOST",
} as const;

export const STAGE_GROUPS: Record<string, string[]> = {
  "Early Lead": [STAGE_CODES.LEAD_SOURCED, STAGE_CODES.REGISTRATION_LINK_SENT],
  Registration: [STAGE_CODES.BUSINESS_REGISTERED, STAGE_CODES.APPLICATION_COMPLETED, STAGE_CODES.FOUNDATION_ONE_CONTRACT_SIGNED],
  "Expression of Interest": [STAGE_CODES.EOI_REQUESTED, STAGE_CODES.EOI_UPLOADED, STAGE_CODES.EOI_SENT_TO_PARTNER, STAGE_CODES.EOI_APPROVED],
  "Utility Review": [STAGE_CODES.UTILITY_BILL_REQUESTED, STAGE_CODES.UTILITY_BILL_UPLOADED, STAGE_CODES.UTILITY_BILL_SENT_TO_PARTNER],
  Proposal: [STAGE_CODES.PROPOSAL_RECEIVED, STAGE_CODES.PROPOSAL_DELIVERED, STAGE_CODES.PROPOSAL_SIGNED, STAGE_CODES.PROPOSAL_SENT_TO_PARTNER],
  "Term Sheet": [STAGE_CODES.TERM_SHEET_RECEIVED, STAGE_CODES.TERM_SHEET_DELIVERED, STAGE_CODES.TERM_SHEET_SIGNED, STAGE_CODES.TERM_SHEET_SENT_TO_PARTNER],
  "Know Your Customer": [STAGE_CODES.KYC_REQUESTED, STAGE_CODES.KYC_UPLOADED, STAGE_CODES.KYC_SENT_TO_PARTNER],
  Approval: [STAGE_CODES.NEDBANK_APPROVED],
  Delivery: [STAGE_CODES.SITE_INSPECTION_STARTED, STAGE_CODES.INSTALLATION_IN_PROGRESS, STAGE_CODES.COMMISSIONED],
  "Live Support": [STAGE_CODES.ACTIVE_SUPPORT],
  Closed: [STAGE_CODES.DISQUALIFIED, STAGE_CODES.LOST],
};

export const DOC_TYPE_CODES = {
  FOUNDATION_ONE_CONTRACT: "FOUNDATION_ONE_CONTRACT",
  EXPRESSION_OF_INTEREST: "EXPRESSION_OF_INTEREST",
  SIX_MONTH_UTILITY_BILL: "SIX_MONTH_UTILITY_BILL",
  PROPOSAL: "PROPOSAL",
  SIGNED_PROPOSAL: "SIGNED_PROPOSAL",
  TERM_SHEET: "TERM_SHEET",
  SIGNED_TERM_SHEET: "SIGNED_TERM_SHEET",
  KYC_DOCUMENT_PACK: "KYC_DOCUMENT_PACK",
  SITE_INSPECTION_PACK: "SITE_INSPECTION_PACK",
  INSTALLATION_COMPLETION_PACK: "INSTALLATION_COMPLETION_PACK",
} as const;

export const HEALTH_STATUS_LABELS: Record<string, string> = {
  HEALTHY: "Healthy",
  AT_RISK: "At Risk",
  STALLED: "Stalled",
  OVERDUE: "Overdue",
  WAITING_ON_BUSINESS: "Waiting on Business",
  WAITING_ON_ADMINISTRATOR: "Waiting on Admin",
  WAITING_ON_PARTNER: "Waiting on Partner",
};

export const KYC_RESTRICTED_DOC_CODES: string[] = [
  DOC_TYPE_CODES.KYC_DOCUMENT_PACK,
];
