import type { AdminAgent, AdminLead, SalesLead } from "@/lib/admin-types";

export const ADMIN_AGENTS: AdminAgent[] = [
  {
    id: "agent-karman",
    name: "Karman",
    role: "Admin",
    region: "National",
  },
];

const LEADS: AdminLead[] = [
  {
    id: "lead-volt-flow",
    clientProfileId: "profile-volt-flow",
    company: "Volt Flow Logistics",
    businessRegistrationNumber: "2018/442331/07",
    industry: "Cold-chain logistics",
    contactName: "Thabo Maseko",
    monthlyElectricitySpendEstimateZar: 186000,
    isBusinessRegistered: true,
    isClientRegistered: true,
    isBusinessOperational: true,
    hasSixMonthUtilityBill: true,
    physicalAddress: "41 Kelvin Drive, Kramerville",
    city: "Johannesburg",
    province: "Gauteng",
    source: "Migrate Portal",
    origin: "created",
    partner: null,
    stage: "Utility Bills Uploaded",
    contactStatus: "Interested",
    priority: "Priority",
    ownerId: "agent-karman",
    linkedSalesLeadId: null,
    readinessScore: 81,
    estimatedValueZar: 2280000,
    lastTouched: "8m ago",
    nextAction: "Upload onboarding term sheet and prep client signature pack.",
    migrateAccountName: "Volt Flow Logistics (Pty) Ltd",
    migrateAccountId: "acct-vflow-001",
    userProfile: {
      id: "usr-vflow-001",
      fullName: "Thabo Maseko",
      email: "thabo.maseko@voltflow.co.za",
      phone: "+27 82 110 4421",
      role: "Owner",
      joinedAt: "2026-04-06",
    },
    eoiSigningToken: "eoi-vflow-001",
    eoiSignedBy: "Thabo Maseko",
    eoiSignedAt: "2026-04-10T08:52:00.000Z",
    eoiAcceptedTermsAt: "2026-04-10T08:52:00.000Z",
    onboardingCompletedAt: null,
    disqualification: null,
    tasks: [
      {
        id: "task-volt-1",
        title: "Book qualification call with ops and finance",
        owner: "Agent",
        dueLabel: "Today",
        status: "open",
      },
      {
        id: "task-volt-2",
        title: "Confirm latest utility schedule upload",
        owner: "Client",
        dueLabel: "Today",
        status: "open",
      },
    ],
    documents: [
      {
        id: "doc-volt-1",
        title: "Utility Bills (Mar-May 2026)",
        category: "Qualification",
        fileType: "PDF",
        status: "reviewed",
        uploadedAt: "Today, 08:48",
        uploadedBy: "T. Maseko (Client)",
        uploadedByType: "Client",
        sourceAccount: "acct-vflow-001",
        sourceWorkspace: "1OS Migrate / Volt Flow",
      },
      {
        id: "doc-volt-2",
        title: "Signed Expression of Interest",
        category: "Onboarding",
        fileType: "PDF",
        status: "signed",
        uploadedAt: "Today, 08:52",
        uploadedBy: "T. Maseko (Client)",
        uploadedByType: "Client",
        sourceAccount: "acct-vflow-001",
        sourceWorkspace: "1OS Migrate / Volt Flow",
      },
      {
        id: "doc-volt-3",
        title: "Roof Imagery Pack",
        category: "Site Data",
        fileType: "PNG",
        status: "received",
        uploadedAt: "Today, 08:56",
        uploadedBy: "B. Radebe (Sales)",
        uploadedByType: "Sales Team",
        sourceAccount: "acct-vflow-001",
        sourceWorkspace: "1OS Migrate / Volt Flow",
      },
    ],
    notes: [
      {
        id: "note-volt-1",
        body: "Client prefers zero-capex positioning and quick implementation timeline.",
        author: "Karman",
        createdAt: "Today, 09:12",
      },
    ],
    events: [
      {
        id: "event-volt-1",
        title: "Lead captured",
        detail: "Lead entered from 1OS Migrate portal intake.",
        createdAt: "Today, 08:58",
        tone: "system",
      },
      {
        id: "event-volt-2",
        title: "Qualification started",
        detail: "Sales accepted the lead and started qualification.",
        createdAt: "Today, 09:10",
        tone: "agent",
      },
    ],
  },
  {
    id: "lead-foundation-crm",
    clientProfileId: "profile-foundation-crm",
    company: "Foundation CRM",
    businessRegistrationNumber: "2020/118904/07",
    industry: "Software operations",
    contactName: "Lara Daniels",
    monthlyElectricitySpendEstimateZar: 146000,
    isBusinessRegistered: true,
    isClientRegistered: true,
    isBusinessOperational: true,
    hasSixMonthUtilityBill: false,
    physicalAddress: "12 Bridgeway, Century City",
    city: "Cape Town",
    province: "Western Cape",
    source: "Migrate Portal",
    origin: "created",
    partner: null,
    stage: "EOI Signed",
    contactStatus: "Contacted",
    priority: "Standard",
    ownerId: "agent-karman",
    linkedSalesLeadId: null,
    readinessScore: 74,
    estimatedValueZar: 1840000,
    lastTouched: "34m ago",
    nextAction: "Upload 6-month utility bill pack to complete onboarding evidence.",
    migrateAccountName: "Foundation CRM South Africa (Pty) Ltd",
    migrateAccountId: "acct-fcrm-009",
    userProfile: {
      id: "usr-fcrm-009",
      fullName: "Lara Daniels",
      email: "lara.daniels@foundationcrm.co.za",
      phone: "+27 72 332 8944",
      role: "Finance Lead",
      joinedAt: "2026-04-05",
    },
    eoiSigningToken: "eoi-fcrm-009",
    eoiSignedBy: "Lara Daniels",
    eoiSignedAt: "2026-04-10T10:20:00.000Z",
    eoiAcceptedTermsAt: "2026-04-10T10:20:00.000Z",
    onboardingCompletedAt: null,
    disqualification: null,
    tasks: [
      {
        id: "task-foundation-crm-1",
        title: "Send signed copy reminder",
        owner: "Agent",
        dueLabel: "Tomorrow",
        status: "open",
      },
      {
        id: "task-foundation-crm-2",
        title: "Prepare revised savings sensitivity",
        owner: "Ops",
        dueLabel: "Tomorrow",
        status: "open",
      },
    ],
    documents: [
      {
        id: "doc-fcrm-1",
        title: "Expression of Interest",
        category: "Onboarding",
        fileType: "PDF",
        status: "issued",
        uploadedAt: "Today, 09:32",
        uploadedBy: "B. Radebe (Sales)",
        uploadedByType: "Sales Team",
        sourceAccount: "acct-fcrm-009",
        sourceWorkspace: "1OS Migrate / Foundation CRM",
      },
      {
        id: "doc-fcrm-2",
        title: "Signed Expression of Interest",
        category: "Onboarding",
        fileType: "PDF",
        status: "signed",
        uploadedAt: "Today, 10:20",
        uploadedBy: "L. Daniels (Client)",
        uploadedByType: "Client",
        sourceAccount: "acct-fcrm-009",
        sourceWorkspace: "1OS Migrate / Foundation CRM",
      },
      {
        id: "doc-fcrm-3",
        title: "Client Registration Pack",
        category: "Onboarding",
        fileType: "DOCX",
        status: "received",
        uploadedAt: "Today, 10:38",
        uploadedBy: "Client Legal",
        uploadedByType: "Client",
        sourceAccount: "acct-fcrm-009",
        sourceWorkspace: "1OS Migrate / Foundation CRM",
      },
    ],
    notes: [
      {
        id: "note-foundation-crm-1",
        body: "Decision-maker asked for a downside case if Eskom tariffs soften.",
        author: "Karman",
        createdAt: "Today, 10:44",
      },
    ],
    events: [
      {
        id: "event-foundation-crm-1",
        title: "Proposal issued",
        detail: "Proposal package shared via portal and email.",
        createdAt: "Today, 10:20",
        tone: "system",
      },
    ],
  },
  {
    id: "lead-clover",
    clientProfileId: "profile-clover",
    company: "Clover SA Manufacturing",
    businessRegistrationNumber: "2011/551209/07",
    industry: "Food manufacturing",
    contactName: "Ravi Singh",
    monthlyElectricitySpendEstimateZar: 402000,
    isBusinessRegistered: true,
    isClientRegistered: true,
    isBusinessOperational: true,
    hasSixMonthUtilityBill: true,
    physicalAddress: "22 North Coast Road, Briardene",
    city: "Durban",
    province: "KwaZulu-Natal",
    source: "Migrate Portal",
    origin: "created",
    partner: null,
    stage: "EOI Generated",
    contactStatus: "Follow Up",
    priority: "Executive",
    ownerId: "agent-karman",
    linkedSalesLeadId: null,
    readinessScore: 67,
    estimatedValueZar: 3650000,
    lastTouched: "2h ago",
    nextAction: "Collect client digital signature on generated EOI.",
    migrateAccountName: "Clover SA Manufacturing (Pty) Ltd",
    migrateAccountId: "acct-clover-014",
    userProfile: {
      id: "usr-clover-014",
      fullName: "Ravi Singh",
      email: "ravi.singh@cloversa.co.za",
      phone: "+27 83 452 1190",
      role: "Operations Lead",
      joinedAt: "2026-04-04",
    },
    eoiSigningToken: "eoi-clover-014",
    eoiSignedBy: null,
    eoiSignedAt: null,
    eoiAcceptedTermsAt: null,
    onboardingCompletedAt: null,
    disqualification: null,
    tasks: [
      {
        id: "task-clover-1",
        title: "Confirm meeting deck with regional load profile",
        owner: "Ops",
        dueLabel: "Today",
        status: "open",
      },
      {
        id: "task-clover-2",
        title: "Invite legal observer for contracting questions",
        owner: "Agent",
        dueLabel: "Today",
        status: "done",
      },
    ],
    documents: [
      {
        id: "doc-clover-1",
        title: "Expression of Interest",
        category: "Onboarding",
        fileType: "PDF",
        status: "issued",
        uploadedAt: "Today, 07:40",
        uploadedBy: "A. Msimang (Sales)",
        uploadedByType: "Sales Team",
        sourceAccount: "acct-clover-014",
        sourceWorkspace: "1OS Migrate / Clover SA",
      },
      {
        id: "doc-clover-2",
        title: "KYC Registration Checklist",
        category: "Onboarding",
        fileType: "PDF",
        status: "received",
        uploadedAt: "Today, 07:42",
        uploadedBy: "R. Singh (Client)",
        uploadedByType: "Client",
        sourceAccount: "acct-clover-014",
        sourceWorkspace: "1OS Migrate / Clover SA",
      },
      {
        id: "doc-clover-3",
        title: "EOI Cover Note",
        category: "Onboarding",
        fileType: "PDF",
        status: "reviewed",
        uploadedAt: "Today, 07:51",
        uploadedBy: "A. Msimang (Sales)",
        uploadedByType: "Sales Team",
        sourceAccount: "acct-clover-014",
        sourceWorkspace: "1OS Migrate / Clover SA",
      },
    ],
    notes: [
      {
        id: "note-clover-1",
        body: "Exec sponsor is engaged; procurement team wants clearer SLA commitments.",
        author: "Karman",
        createdAt: "Today, 08:06",
      },
    ],
    events: [
      {
        id: "event-clover-1",
        title: "Demo requested",
        detail: "Client requested tailored technical walkthrough.",
        createdAt: "Today, 07:58",
        tone: "client",
      },
    ],
  },
  {
    id: "lead-foundation-hub",
    clientProfileId: "profile-foundation-hub",
    company: "Foundation Solar Hub",
    businessRegistrationNumber: "2016/308017/07",
    industry: "Industrial campus",
    contactName: "Khumo Ncube",
    monthlyElectricitySpendEstimateZar: 512000,
    isBusinessRegistered: true,
    isClientRegistered: true,
    isBusinessOperational: true,
    hasSixMonthUtilityBill: true,
    physicalAddress: "9 Atlas Road, Jet Park",
    city: "Ekurhuleni",
    province: "Gauteng",
    source: "Migrate Portal",
    origin: "created",
    partner: null,
    stage: "Term Sheet Uploaded",
    contactStatus: "Interested",
    priority: "Executive",
    ownerId: "agent-karman",
    linkedSalesLeadId: null,
    readinessScore: 88,
    estimatedValueZar: 6210000,
    lastTouched: "1h ago",
    nextAction: "Confirm final onboarding checks and move lead to onboarding complete.",
    migrateAccountName: "Foundation Solar Hub (Pty) Ltd",
    migrateAccountId: "acct-fhub-021",
    userProfile: {
      id: "usr-fhub-021",
      fullName: "Khumo Ncube",
      email: "khumo.ncube@foundationsolarhub.co.za",
      phone: "+27 79 214 5560",
      role: "Owner",
      joinedAt: "2026-04-03",
    },
    eoiSigningToken: "eoi-fhub-021",
    eoiSignedBy: "Khumo Ncube",
    eoiSignedAt: "2026-04-09T10:06:00.000Z",
    eoiAcceptedTermsAt: "2026-04-09T10:06:00.000Z",
    onboardingCompletedAt: null,
    disqualification: null,
    tasks: [
      {
        id: "task-hub-1",
        title: "Review redlines with legal",
        owner: "Legal",
        dueLabel: "Today",
        status: "open",
      },
      {
        id: "task-hub-2",
        title: "Validate margin guardrails",
        owner: "Ops",
        dueLabel: "Today",
        status: "open",
      },
    ],
    documents: [
      {
        id: "doc-hub-1",
        title: "Signed Proposal",
        category: "Commercials",
        fileType: "PDF",
        status: "signed",
        uploadedAt: "Today, 10:06",
        uploadedBy: "K. Ncube (Client)",
        uploadedByType: "Client",
        sourceAccount: "acct-fhub-021",
        sourceWorkspace: "1OS Migrate / Foundation Solar Hub",
      },
      {
        id: "doc-hub-2",
        title: "Term Sheet Draft v3",
        category: "Legal",
        fileType: "PDF",
        status: "issued",
        uploadedAt: "Today, 10:16",
        uploadedBy: "A. Singh (Sales)",
        uploadedByType: "Sales Team",
        sourceAccount: "acct-fhub-021",
        sourceWorkspace: "1OS Migrate / Foundation Solar Hub",
      },
      {
        id: "doc-hub-3",
        title: "Redline Matrix",
        category: "Legal",
        fileType: "XLSX",
        status: "reviewed",
        uploadedAt: "Today, 10:41",
        uploadedBy: "Client Legal",
        uploadedByType: "Client",
        sourceAccount: "acct-fhub-021",
        sourceWorkspace: "1OS Migrate / Foundation Solar Hub",
      },
    ],
    notes: [
      {
        id: "note-hub-1",
        body: "Commercial momentum is strong; one liability clause remains open.",
        author: "Karman",
        createdAt: "Today, 11:04",
      },
    ],
    events: [
      {
        id: "event-hub-1",
        title: "Contract negotiation opened",
        detail: "Client legal team returned first redline package.",
        createdAt: "Today, 10:42",
        tone: "client",
      },
    ],
  },
  {
    id: "lead-apex",
    clientProfileId: "profile-apex",
    company: "Apex Milling",
    businessRegistrationNumber: "2014/290118/07",
    industry: "Food processing",
    contactName: "Palesa Khumalo",
    monthlyElectricitySpendEstimateZar: 240000,
    isBusinessRegistered: true,
    isClientRegistered: true,
    isBusinessOperational: true,
    hasSixMonthUtilityBill: true,
    physicalAddress: "77 Bronkhorst Street, Arcadia",
    city: "Pretoria",
    province: "Gauteng",
    source: "Referral",
    origin: "created",
    partner: null,
    stage: "Onboarding Complete",
    contactStatus: "Converted",
    priority: "Standard",
    ownerId: "agent-karman",
    linkedSalesLeadId: null,
    readinessScore: 95,
    estimatedValueZar: 1720000,
    lastTouched: "Yesterday",
    nextAction: "Transition account to implementation and customer success.",
    migrateAccountName: "Apex Milling Holdings (Pty) Ltd",
    migrateAccountId: "acct-apex-030",
    userProfile: {
      id: "usr-apex-030",
      fullName: "Palesa Khumalo",
      email: "palesa.khumalo@apexmilling.co.za",
      phone: "+27 76 802 4459",
      role: "Owner",
      joinedAt: "2026-04-01",
    },
    eoiSigningToken: "eoi-apex-030",
    eoiSignedBy: "Palesa Khumalo",
    eoiSignedAt: "2026-04-08T15:42:00.000Z",
    eoiAcceptedTermsAt: "2026-04-08T15:42:00.000Z",
    onboardingCompletedAt: "2026-04-09T15:42:00.000Z",
    disqualification: null,
    tasks: [
      {
        id: "task-apex-1",
        title: "Schedule delivery handover",
        owner: "Agent",
        dueLabel: "Tomorrow",
        status: "open",
      },
    ],
    documents: [
      {
        id: "doc-apex-1",
        title: "Signed Expression of Interest",
        category: "Onboarding",
        fileType: "PDF",
        status: "signed",
        uploadedAt: "Yesterday, 15:42",
        uploadedBy: "P. Khumalo (Client)",
        uploadedByType: "Client",
        sourceAccount: "acct-apex-030",
        sourceWorkspace: "1OS Migrate / Apex Milling",
      },
      {
        id: "doc-apex-2",
        title: "6-Month Utility Bill Pack",
        category: "Qualification",
        fileType: "PDF",
        status: "reviewed",
        uploadedAt: "Yesterday, 15:51",
        uploadedBy: "N. Mkhize (Sales)",
        uploadedByType: "Sales Team",
        sourceAccount: "acct-apex-030",
        sourceWorkspace: "1OS Migrate / Apex Milling",
      },
      {
        id: "doc-apex-3",
        title: "Onboarding Term Sheet",
        category: "Legal",
        fileType: "PDF",
        status: "signed",
        uploadedAt: "Yesterday, 16:04",
        uploadedBy: "P. Khumalo (Client)",
        uploadedByType: "Client",
        sourceAccount: "acct-apex-030",
        sourceWorkspace: "1OS Migrate / Apex Milling",
      },
    ],
    notes: [
      {
        id: "note-apex-1",
        body: "Won after second commercial revision; ideal case study candidate.",
        author: "Karman",
        createdAt: "Yesterday, 16:21",
      },
    ],
    events: [
      {
        id: "event-apex-1",
        title: "Deal won",
        detail: "Signed terms received and moved into implementation queue.",
        createdAt: "Yesterday, 16:18",
        tone: "system",
      },
    ],
  },
];

const SALES_LEADS: SalesLead[] = [
  {
    id: "sales-lead-vanguard",
    ownerId: "agent-karman",
    linkedAdminLeadId: null,
    createdByRole: "sales",
    createdByEmail: null,
    contactName: "Ayanda Molefe",
    company: "Vanguard Foods",
    email: "ayanda.molefe@vanguardfoods.co.za",
    qualificationStage: "Interested",
    qualificationReason: null,
    status: "Open",
    createdAt: "2026-04-11T08:20:00.000Z",
    lastUpdatedAt: "2026-04-11T10:05:00.000Z",
    convertedClientProfileId: null,
  },
  {
    id: "sales-lead-pivot",
    ownerId: "agent-karman",
    linkedAdminLeadId: null,
    createdByRole: "sales",
    createdByEmail: null,
    contactName: "Nomvula Dlamini",
    company: "Pivot Water Systems",
    email: "nomvula@pivotwater.co.za",
    qualificationStage: "Qualifies",
    qualificationReason: null,
    status: "Open",
    createdAt: "2026-04-12T11:15:00.000Z",
    lastUpdatedAt: "2026-04-13T07:42:00.000Z",
    convertedClientProfileId: null,
  },
  {
    id: "sales-lead-axis",
    ownerId: "agent-karman",
    linkedAdminLeadId: null,
    createdByRole: "sales",
    createdByEmail: null,
    contactName: "Thulani Moyo",
    company: "Axis Cold Rooms",
    email: "thulani@axiscoldrooms.co.za",
    qualificationStage: "Havent Contacted",
    qualificationReason: null,
    status: "Open",
    createdAt: "2026-04-10T13:50:00.000Z",
    lastUpdatedAt: "2026-04-10T13:50:00.000Z",
    convertedClientProfileId: null,
  },
];

export function createAdminSeedLeads(): AdminLead[] {
  if (typeof structuredClone === "function") {
    return structuredClone(LEADS);
  }

  return JSON.parse(JSON.stringify(LEADS)) as AdminLead[];
}

export function createAdminSeedSalesLeads(): SalesLead[] {
  if (typeof structuredClone === "function") {
    return structuredClone(SALES_LEADS);
  }

  return JSON.parse(JSON.stringify(SALES_LEADS)) as SalesLead[];
}
