-- Foundation-1 learning loop: engine calibration ledger, reader-correction
-- capture and the stored weekly operating brief.
--
-- Additive only. Nothing here touches migration-case stages, calculations,
-- signatures, submissions or term-sheet decisions. All tables are
-- service-role-only (RLS) like the rest of the intelligence layer, and every
-- reader/writer in lib/intelligence degrades gracefully when this migration
-- has not been applied yet.

-- 1. ENGINE CALIBRATION LEDGER -----------------------------------------
-- One row per funder-report cross-check: the funder's stated figure vs the
-- clone-engine prediction for the same case. Feeds the rolling per-field
-- drift rule in lib/intelligence/learning-loop.ts.
create table if not exists public.foundation1_engine_calibration (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  environment text not null default 'production',
  case_reference text not null,
  source text not null,
  field text not null,
  predicted numeric,
  stated numeric,
  deviation_pct numeric,
  tolerance_pct numeric not null default 2,
  pass boolean,
  report_version text not null default '',
  operator_confirmed boolean not null default false,
  constraint foundation1_engine_calibration_environment_check
    check (environment in ('production', 'preview', 'development', 'test')),
  constraint foundation1_engine_calibration_source_check
    check (source in ('ufms', 'wheeling')),
  constraint foundation1_engine_calibration_field_check
    check (length(field) between 1 and 80),
  constraint foundation1_engine_calibration_reference_check
    check (length(case_reference) between 1 and 80)
);

create index if not exists foundation1_engine_calibration_field_created_idx
  on public.foundation1_engine_calibration (source, field, created_at desc);
create index if not exists foundation1_engine_calibration_case_idx
  on public.foundation1_engine_calibration (case_reference, created_at desc);

-- 2. READER CORRECTION CAPTURE ------------------------------------------
-- Labelled examples: the machine's original extracted value vs the value the
-- operator corrected it to (funder-report confirm path today; bill
-- operator-correction paths reuse source = 'bill').
create table if not exists public.foundation1_reader_corrections (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  environment text not null default 'production',
  case_reference text not null,
  source text not null,
  field text not null,
  original_value numeric,
  corrected_value numeric,
  corrected_by text not null default '',
  context jsonb not null default '{}'::jsonb,
  constraint foundation1_reader_corrections_environment_check
    check (environment in ('production', 'preview', 'development', 'test')),
  constraint foundation1_reader_corrections_source_check
    check (source in ('funder_report', 'bill')),
  constraint foundation1_reader_corrections_field_check
    check (length(field) between 1 and 80),
  constraint foundation1_reader_corrections_reference_check
    check (length(case_reference) between 1 and 80)
);

create index if not exists foundation1_reader_corrections_field_created_idx
  on public.foundation1_reader_corrections (source, field, created_at desc);

-- 3. WEEKLY OPERATING BRIEF ----------------------------------------------
-- One deterministic Monday brief per week and environment, generated by the
-- existing 03:00 UTC learning-cycle cron (only when it is Monday) or
-- manually from /admin/intelligence. Markdown is INTERNAL.
create table if not exists public.foundation1_weekly_briefs (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  week_start date not null,
  environment text not null default 'production',
  markdown text not null,
  metrics jsonb not null default '{}'::jsonb,
  generator_version text not null default '',
  constraint foundation1_weekly_briefs_environment_check
    check (environment in ('production', 'preview', 'development', 'test')),
  unique (week_start, environment)
);

create index if not exists foundation1_weekly_briefs_week_idx
  on public.foundation1_weekly_briefs (environment, week_start desc);

-- Service-role only, like the rest of the intelligence schema. -----------
alter table public.foundation1_engine_calibration enable row level security;
alter table public.foundation1_reader_corrections enable row level security;
alter table public.foundation1_weekly_briefs enable row level security;

revoke all on table public.foundation1_engine_calibration from anon, authenticated;
revoke all on table public.foundation1_reader_corrections from anon, authenticated;
revoke all on table public.foundation1_weekly_briefs from anon, authenticated;

grant all on table public.foundation1_engine_calibration to service_role;
grant all on table public.foundation1_reader_corrections to service_role;
grant all on table public.foundation1_weekly_briefs to service_role;

drop policy if exists "service role manages foundation1 engine calibration"
  on public.foundation1_engine_calibration;
create policy "service role manages foundation1 engine calibration"
on public.foundation1_engine_calibration for all to service_role using (true) with check (true);

drop policy if exists "service role manages foundation1 reader corrections"
  on public.foundation1_reader_corrections;
create policy "service role manages foundation1 reader corrections"
on public.foundation1_reader_corrections for all to service_role using (true) with check (true);

drop policy if exists "service role manages foundation1 weekly briefs"
  on public.foundation1_weekly_briefs;
create policy "service role manages foundation1 weekly briefs"
on public.foundation1_weekly_briefs for all to service_role using (true) with check (true);
